### ISSUE TITLE
error getting on run command on Windows: rocker --x11 --privileged turtlebot3_container terminator

### ISSUE THREAD

**Issue by HasibuzzamanFUAS** [vinay06vinay/Turtlebot3-Obstacle-Avoidance-ROS2#1]
```
C:\Users\HasibuzzamanHasibuzz\Downloads\Personal Files\Hasib\FraUAS MEng. Info\wi2425\AIS\Turtlebot3-Obstacle-Avoidance-ROS2>rocker --x11 --privileged turtlebot3_container terminator
Traceback (most recent call last):
  File "C:\Users\HasibuzzamanHasibuzz\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\HasibuzzamanHasibuzz\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\HasibuzzamanHasibuzz\AppData\Local\Programs\Python\Python310\Scripts\rocker.exe\__main__.py", line 4, in <module>
  File "C:\Users\HasibuzzamanHasibuzz\AppData\Local\Programs\Python\Python310\lib\site-packages\rocker\cli.py", line 19, in <module>
    from .core import DockerImageGenerator
  File "C:\Users\HasibuzzamanHasibuzz\AppData\Local\Programs\Python\Python310\lib\site-packages\rocker\core.py", line 18, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'

C:\Users\HasibuzzamanHasibuzz\Downloads\Personal Files\Hasib\FraUAS MEng. Info\wi2425\AIS\Turtlebot3-Obstacle-Avoidance-ROS2>
```

## Can you help please ? Is it posible to run this comand on windows system ?

**Comment by vinay06vinay** [comment]
Hi,

The Rocker installation required for running the container to enable the display access of the host system to the container. Unfortunately rocker is build for linux systems. So, the rocker command wouldn't work. I have updated the instructions on running the container without using rocker. Please refer to it. 

Also, if you wish to run it on Linux only you can use WSL on windows too

**Comment by HasibuzzamanFUAS** [comment]
Thanks for your quick response and the issue is solved. I used docker-compose instead of rocker and it runs nice.

Note that: I have tried the distro like ubuntu 22.04 on windows but i faced also the same error to run rocker to import 'pwd' module. then i changed mind to use the docker-compose.
